### ISSUE TITLE
Athena transport duplicate message

### ISSUE THREAD

**Issue by jonathanj** [twisted/nevow#57] opened 2015-10-22 13:09 UTC
What information is this logged message supposed to convey?

Looking at the code it seems like there are some cases where an old message is trying to be retransmitted but I don't fully understand why this would occur. Is this just normal operation or is it an issue that should be resolved?

Either way, currently our logs are absolutely flooded with this message and it doesn't provide any benefit. Can it be removed or resolved, if it is in fact a bug?

**Comment by mithrandi** [comment] 2015-10-22 20:36
The log message itself is entirely useless to users of Athena, so I think it should be removed.

I believe the cause of the flood of messages that can sometimes be observed is this:
- Retransmits are checked for every time a message is processed.
- Multiple messages are sent in the same basket.
- The server ACKs all of the messages in the same basket.
- The client processes the first ack, retransmits messages 2 and onwards.
- The client processes the second ack, retransmits messages 3 and onwards.
- The client processes the third ack, retransmits messages 4 and onwards.
- etc.

Fixing this issue is a bit more tricky, but should probably be a separate issue from removing the log message.

**Comment by mithrandi** [comment] 2018-05-22 06:26
Fixed in #63.

**Closed by mithrandi** 2018-05-22 06:26 UTC
